# Generated by Django 4.1.10 on 2023-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("dob", models.DateTimeField(auto_now=True)),
                ("email", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created"],},
        ),
    ]
