# Generated by Django 4.1.10 on 2023-07-30 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farmRestFullAPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="author",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="control_panel",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "Published")], default=1, max_length=2
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
