# Generated by Django 4.1.10 on 2023-08-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmRestFullAPI", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_you",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
