# Generated by Django 4.1.10 on 2023-08-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmRestFullAPI', '0010_automation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enableAutomation', models.BooleanField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
